### ISSUE TITLE
Sample application does not build

### ISSUE THREAD

**Issue by brianyyz** [IBM-Swift/Kitura-Credentials-Sample#27]
I cloned the Kitura-Credentials-Sample from Github and tried to build. 

Output of Swift Build on High Sierra 10.13.6 follows.

There seems to be a reference somewhere to Kituranet (as opposed to Kitura-net) and KituraTemplateEngine (as opposed to Kitura-TemplateEngine) which I'm having trouble finding to correct. Any help / pointers much appreciated.

MacBook-Air:Kitura-Credentials-Sample Brian$ swift build
Fetching https://github.com/IBM-Swift/CEpoll.git
Fetching https://github.com/IBM-Swift/Kitura.git
Fetching https://github.com/IBM-Swift/KituraContracts.git
Fetching https://github.com/IBM-Swift/BlueSignals.git
Fetching https://github.com/IBM-Swift/Kitura-net.git
Fetching https://github.com/IBM-Swift/Kitura-CredentialsFacebook.git
Fetching https://github.com/IBM-Swift/Kitura-Session.git
Fetching https://github.com/IBM-Swift/LoggerAPI.git
Fetching https://github.com/IBM-Swift/CCurl.git
Fetching https://github.com/IBM-Swift/SwiftyJSON.git
Fetching https://github.com/IBM-Swift/CommonCrypto.git
Fetching https://github.com/IBM-Swift/Kitura-Credentials.git
Fetching https://github.com/IBM-Swift/Kitura-CredentialsGoogle.git
Fetching https://github.com/IBM-Swift/OpenSSL.git
Fetching https://github.com/IBM-Swift/BlueSSLService.git
Fetching https://github.com/IBM-Swift/BlueSocket.git
Fetching https://github.com/IBM-Swift/BlueCryptor.git
Fetching https://github.com/IBM-Swift/HeliumLogger.git
Fetching https://github.com/IBM-Swift/Kitura-CredentialsHTTP.git
Fetching https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Cloning https://github.com/IBM-Swift/Kitura.git
Resolving https://github.com/IBM-Swift/Kitura.git at 2.0.0
Cloning https://github.com/IBM-Swift/KituraContracts.git
Resolving https://github.com/IBM-Swift/KituraContracts.git at 0.0.14
Cloning https://github.com/IBM-Swift/Kitura-net.git
Resolving https://github.com/IBM-Swift/Kitura-net.git at 1.7.18
Cloning https://github.com/IBM-Swift/Kitura-CredentialsFacebook.git
Resolving https://github.com/IBM-Swift/Kitura-CredentialsFacebook.git at 2.0.0
Cloning https://github.com/IBM-Swift/Kitura-Session.git
Resolving https://github.com/IBM-Swift/Kitura-Session.git at 2.0.0
Cloning https://github.com/IBM-Swift/LoggerAPI.git
Resolving https://github.com/IBM-Swift/LoggerAPI.git at 1.7.1
Cloning https://github.com/IBM-Swift/CCurl.git
Resolving https://github.com/IBM-Swift/CCurl.git at 0.4.1
Cloning https://github.com/IBM-Swift/SwiftyJSON.git
Resolving https://github.com/IBM-Swift/SwiftyJSON.git at 17.0.0
Cloning https://github.com/IBM-Swift/CommonCrypto.git
Resolving https://github.com/IBM-Swift/CommonCrypto.git at 0.1.5
Cloning https://github.com/IBM-Swift/Kitura-Credentials.git
Resolving https://github.com/IBM-Swift/Kitura-Credentials.git at 2.0.0
Cloning https://github.com/IBM-Swift/BlueSSLService.git
Resolving https://github.com/IBM-Swift/BlueSSLService.git at 0.12.64
Cloning https://github.com/IBM-Swift/Kitura-CredentialsGoogle.git
Resolving https://github.com/IBM-Swift/Kitura-CredentialsGoogle.git at 2.0.0
Cloning https://github.com/IBM-Swift/BlueSocket.git
Resolving https://github.com/IBM-Swift/BlueSocket.git at 0.12.76
Cloning https://github.com/IBM-Swift/BlueCryptor.git
Resolving https://github.com/IBM-Swift/BlueCryptor.git at 0.8.18
Cloning https://github.com/IBM-Swift/Kitura-CredentialsHTTP.git
Resolving https://github.com/IBM-Swift/Kitura-CredentialsHTTP.git at 2.0.0
Cloning https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Resolving https://github.com/IBM-Swift/Kitura-TemplateEngine.git at 1.7.2
Cloning https://github.com/IBM-Swift/HeliumLogger.git
Resolving https://github.com/IBM-Swift/HeliumLogger.git at 1.7.1
'Kitura' /Users/Brian/Documents/DevelopmentProjects/Kitura/Kitura-Credentials-Sample/.build/checkouts/Kitura.git-6522211175291160341: error: product dependency 'KituraNet' not found
'Kitura' /Users/Brian/Documents/DevelopmentProjects/Kitura/Kitura-Credentials-Sample/.build/checkouts/Kitura.git-6522211175291160341: error: product dependency 'KituraTemplateEngine' not found
MacBook-Air:Kitura-Credentials-Sample Brian$

**Comment by ianpartridge** [comment]
Oops, sorry about that! Fixed in #28 please try again :)

**Comment by brianyyz** [comment]
Thanks Ian!
