### ISSUE TITLE
Update to Swift 4 & Add Test Cases

### ISSUE THREAD

**Issue by neurosaurus** [IBM-Swift/Kitura-Credentials-Sample#29]
This sample app was quite useful for me!

Any chance it can be updated to Swift 4? 

Also, it would be helpful if there were some unit tests for the plugin within the demo app. `authenticate` requires a `request` and a `response` as parameters and creating mocks for those looks a bit complicated.

**Comment by ianpartridge** [comment]
Hi @neurosaurus I think it should already run on Swift 4 - what errors are you seeing?

**Comment by christiancompton** [comment]
@ianpartridge It looks like this PR should do the 4.1.2 update https://github.com/IBM-Swift/Kitura-Credentials-Sample/pull/26

Are there simple unit tests for the Kitura Credentials plugin (`authenticate`, `request`, `response`)?  The only ones I can find seem to have very complex mocking mechanisms.

**Comment by Andrew-Lees11** [comment]
We are deprecating this repo. A replacement example which uses swift 4 and has tests is available in [Kitura-Sample](https://github.com/IBM-Swift/Kitura-Sample).
